- import_tasks: pre.yaml

- name: ORG -> Create wanted repo directories
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/work/{{ item.path }}"
    state: directory
    mode: '0755'
  loop: "{{ repos_org.projects }}"


- name: ORG -> Clone org repos
  ansible.builtin.git:
    repo: "{{ project_url.1 }}"
    dest: "{{ ansible_env.HOME }}/work/{{ project_url.0.path }}/{{ (project_url.1 | basename | splitext).0 }}"
    accept_hostkey: yes
  loop: "{{ lookup('subelements', repos_org.projects, 'urls') }}"
  loop_control:
    loop_var: project_url
  environment:
    SSH_AUTH_SOCK: "{{ ssh_auth_sock | default(lookup('env','SSH_AUTH_SOCK') | default('')) }}"
