- name: Ensure SSH agent socket is available for repos
  ansible.builtin.set_fact:
    ssh_auth_sock: "{{ ssh_auth_sock | default(lookup('env','SSH_AUTH_SOCK') | default('')) }}"

- name: Fail if no SSH agent socket is available
  ansible.builtin.fail:
    msg: "SSH agent not available. Ensure the ssh role ran (it starts an agent) or export SSH_AUTH_SOCK."
  when: (ssh_auth_sock | default('')) | length == 0


