- hosts: localhost
  connection: local
  become: true
  roles:
    - system

- hosts: localhost
  connection: local
  become: true
  become_user: "{{ user.name }}"

  roles:
    - filesystem
    - role: packages
      become: true
      become_user: root
      become_method: sudo
    - binaries
    - ssh
    - gpg
    - dotfiles
    - stow
    #- repos

