- name: Base system setup
  hosts: localhost
  connection: local
  become: true
  roles:
    - system

- name: User bootstrap
  hosts: localhost
  connection: local
  become: true
  become_user: "{{ bootstrap_user_name | default(vault_org.user.name | default(user.name)) }}"
  gather_facts: true

  roles:
    - filesystem
    - role: packages
      become: true
      become_user: root
      become_method: sudo
    - binaries
    - ssh
    - gpg
    - dotfiles
    - stow
    - repos
    - post-install
