- hosts: localhost
  connection: local
  become: true
  roles:
    - system

- hosts: localhost
  connection: local
  become_user: "{{ user.name }}"
  pre_tasks:
    - name: Build ssh keys entry list
      vars:
        base_ssh_keys: "{{ ssh_keys | default([]) }}"
        org_ssh_keys:  "{{ ssh_keys_org | default([]) }}"
      set_fact:
        ssh_keys: "{{ base_ssh_keys + org_ssh_keys }}"

    - name: Build ssh config entry list
      vars:
        base_ssh_config: "{{ ssh_config | default([]) }}"
        org_ssh_config:  "{{ ssh_config_org | default([]) }}"
      set_fact:
        ssh_config: "{{ base_ssh_config + org_ssh_config }}"

    - name: Build package list
      vars:
        core_list: "{{ packages.core | default([]) }}"
        full_list: "{{ packages.full | default([]) }}"
        org_list: "{{ packages_org | default([]) }}"
      set_fact:
        packages: "{{ core_list + full_list + org_list }}"

    - name: Build directories list
      vars:
        dirs: "{{ filesystem.directories | default([]) }}"
        org_dirs: "{{ filesystem_org.directories | default([]) }}"
      set_fact:
        directories: "{{ dirs + org_dirs }}"

    - name: Build binaries list
      vars:
        bins: "{{ binaries | default([]) | list }}"
        org_bins: "{{ binaries_org | default([]) | list }}"
      set_fact:
        binaries: "{{ bins + org_bins }}"

  roles:
    - filesystem
    - packages
    - binaries
    - ssh
    - gpg
    - dotfiles
    - stow
