- name: Build package list
  vars:
    minimal_list: "{{ packages.minimal | default([]) }}"
    full_list: "{{ packages.full | default([]) }}"
    org_list: "{{ packages_org | default([]) }}"
  set_fact:
    packages: "{{ minimal_list + full_list + org_list }}"
