- name: Stow dotfiles core packages
  shell: "stow -t {{ ansible_env.HOME }} {{ item }}"
  args:
    chdir: "{{ ansible_env.HOME }}/.dots-core"
  with_items: "{{ stow.core }}"
  register: stow_result_core
  changed_when: stow_result_core is changed

- name: Stow dotfiles packages
  shell: "stow -t {{ ansible_env.HOME }} {{ item }}"
  args:
    chdir: "{{ ansible_env.HOME }}/.dots"
  with_items: "{{ stow.full }}"
  register: stow_result_full
  changed_when: stow_result_full is changed

- name: Stow dotfiles packages extras
  shell: "stow -t {{ ansible_env.HOME }} {{ item }}"
  args:
    chdir: "{{ ansible_env.HOME }}/.dots-org"
  with_items: "{{ stow_org }}"
  register: stow_result_org
  changed_when: stow_result_org is changed
