- name: Ensure ~/.ssh dir exists
  file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: '0700'

- name: Add GitHub to known_hosts (prevent host key prompt)
  ansible.builtin.shell: |
    ssh-keyscan -t rsa,ecdsa,ed25519 github.com >> ~/.ssh/known_hosts
  args:
    creates: "{{ ansible_env.HOME }}/.ssh/known_hosts"

## PERSONAL
- name: Install private SSH keys
  copy:
    dest: "{{ ansible_env.HOME }}/.ssh/{{ item.name }}"
    content: "{{ item.private }}"
    mode: '0600'
  when: item.private is defined
  loop: "{{ ssh_keys }}"
  #no_log: true

- name: Add key
  ansible.builtin.shell: |
    eval "$(ssh-agent -s)"
    ssh-add "{{ ansible_env.HOME }}/.ssh/{{ item.name }}"
  when: item.private is defined
  loop: "{{ ssh_keys }}"
  environment:
    SSH_AUTH_SOCK: /tmp/ssh-agent.sock
  args:
    executable: /bin/bash
  changed_when: false
