- name: Ensure ~/.ssh dir exists
  file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: '0700'

- name: Install private SSH keys
  copy:
    dest: "{{ ansible_env.HOME }}/.ssh/{{ item.name }}"
    content: "{{ item.private }}"
    mode: '0600'
  when: item.private is defined
  loop: "{{ ssh_keys }}"
  no_log: true

- name: Install public SSH keys
  copy:
    dest: "{{ ansible_env.HOME }}/.ssh/{{ item.name }}.pub"
    content: "{{ item.public }}"
    mode: '0644'
  when: item.public is defined
  loop: "{{ ssh_keys }}"
  no_log: true

- name: Install private SSH keys org
  copy:
    dest: "{{ ansible_env.HOME }}/.ssh/{{ item.name }}"
    content: "{{ item.private }}"
    mode: '0600'
  when: item.private is defined
  loop: "{{ ssh_keys_org }}"
  no_log: true

- name: Install public SSH keys org
  copy:
    dest: "{{ ansible_env.HOME }}/.ssh/{{ item.name }}.pub"
    content: "{{ item.public }}"
    mode: '0644'
  when: item.public is defined
  loop: "{{ ssh_keys_org }}"
  no_log: true


