- name: Build ssh keys entry list
  vars:
    base_ssh_keys: "{{ vault.ssh_keys | default([]) }}"
    org_ssh_keys:  "{{ vault_org.ssh_keys | default([]) }}"
  set_fact:
    ssh_keys: "{{ base_ssh_keys + org_ssh_keys }}"

- name: Ensure ssh-agent is running and capture socket/pid
  ansible.builtin.shell: |
    if [ -n "$SSH_AUTH_SOCK" ] && [ -S "$SSH_AUTH_SOCK" ]; then
      echo "$SSH_AUTH_SOCK|$SSH_AGENT_PID"
    else
      eval "$(ssh-agent -s)" >/dev/null
      echo "$SSH_AUTH_SOCK|$SSH_AGENT_PID"
    fi
  args:
    executable: /bin/bash
  register: ssh_agent_env
  changed_when: false

- name: Export SSH agent variables for SSH role
  ansible.builtin.set_fact:
    ssh_auth_sock: "{{ (ssh_agent_env.stdout | default('')) | regex_search('^([^|]+)') }}"
    ssh_agent_pid: "{{ (ssh_agent_env.stdout | default('')) | regex_search('[^|]+$') }}"
