- name: Build ssh keys entry list
  vars:
    base_ssh_keys: "{{ ssh_keys | default([]) }}"
    org_ssh_keys:  "{{ ssh_keys_org | default([]) }}"
  set_fact:
    ssh_keys: "{{ base_ssh_keys + org_ssh_keys }}"
