filesystem_org:
  directories::
    - ~/code/work
  stow:
    - pass
    - glab-cli
    - taskwarrior
    - bugwarrior
    - timewarrior

repos_org:
  dots: github.com:antonlundstroem/dots-aceve.git

packages_org:
  - openssh-client
  #- argocd
  # - glab
  # - dotnet
#- 1password-cli -- mirrors have to be added
  # cursor-agent
  #

